name: stop
help: Stop service remove service containers.
filename: commands/stop
catch_all: "Arbitrary options for the 'docker compose stop' command."
filters:
  - is_laravel_root
  - project_is_initialized
  - has_env_file
  - templates_are_rendered
