#!/usr/bin/env bash
set -e

run_hook "before_nuke"

if [ $APP_ENV != "local" ] && [[ ${args[--force]} != 1 ]];
then
    warning "Your application env is '$APP_ENV', This will remove $(underlined $(bold ALL)) compose services, volumes and images, Are you sure? (y|Y)"
    read -p "" -n 1 -r
    echo   
    if [[ ! $REPLY =~ ^[Yy]$ ]]
    then
        red "Aborted."
        exit 1
    fi
fi


file_args="-f .larawind/rendered/compose/app.yaml"
services_path="$(larawind_path rendered/compose)"
env_file=".larawind/rendered/compose/$APP_ENV.env.yaml"

if [ -f $env_file ]
then
    info "Discovered service file: $env_file"
    file_args="$file_args -f $env_file"
fi

for service_file in $(find $services_path -type f -name *.yaml ! -name app.yaml ! -name $APP_ENV.env.yaml)
do
    path=".larawind/$(str_after "$service_file" ".larawind/")"
    file_args="$file_args -f $path"
    info "Discovered service file: $path"
done

docker compose $file_args down --rmi all -v ${other_args[@]}

if [ $? -eq 0 ]; then
    info "Nuked services. Consider running 'docker system prune' to remove dangling resources."
    run_hook "after_nuke"
fi

set +e