version: "3.8"
services:
  app:
    image: {{ $appImage }}
    container_name: {{ $dockerTagNamespace }}-app
    restart: unless-stopped
    tty: true
    env_file: ../../../.env
    environment:
      COMPOSER_MEMORY_LIMIT: -1
    ports:
      - "9000:9000"
      @if($appEnv == 'local')
      - "${VITE_PORT:-3000}:3000" 
      @endif
    volumes:
      - ../../../:/var/www/html
      - ../nginx/ssl:{{ $dockerSslDirectory }}
      - ../php.ini:/etc/php/8.1/fpm/conf.d/php-{{ $dockerTagNamespace }}.ini
      - ../php-fpm.conf:/etc/php/8.1/fpm/pool.d/www.conf
    networks:
      - {{ $dockerTagNamespace }}-network
    depends_on:
      - redis
      - mysql
    healthcheck: 
      test: ["CMD-SHELL",  "service php8.1-fpm status || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 5
