version: "3.8"
services:
  nginx:
    image: {{ $nginxImage }}
    container_name: {{ $dockerTagNamespace }}-nginx
    restart: unless-stopped
    env_file: ../../../.env
    tty: true
    ports:
      - "{{ $nginxHostHttpPort }}:80"
      - "{{ $nginxHostHttpsPort }}:443"
    volumes:
      - ../../../:/var/www/html
      - ../nginx/conf.d:/etc/nginx/conf.d
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../nginx/ssl:{{ $dockerSslDirectory }}
    networks:
      - {{ $dockerTagNamespace }}-network
    healthcheck: 
      test: ["CMD-SHELL",  "curl -L --insecure http://{{$domain}}:80"]
      interval: 10s
      timeout: 15s
      retries: 5
